#!/bin/sh

case "$1" in
start)
java -jar /home/pushservice_fat.jar &
echo $! > /var/run/pushservice_fat.pid
;;

stop)
if [ ! -f /var/run/pushservice_fat.pid ]; then
echo "pushservice_fat: not running"
exit 1
fi

kill -TERM `cat /var/run/pushservice_fat.pid`
;;

reload)
if [ ! -f /var/run/pushservice_fat.pid ]; then
echo "pushservice_fat: not running"
exit 1
fi

kill -HUP `cat /var/run/pushservice_fat.pid`
;;

*)
echo "Usage: /etc/init.d/pushservice {start|stop|reload}"
exit 1
;;

esac

exit 0